# Generated by Django 4.2.7 on 2026-03-31 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_transactionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingsgoal',
            name='withdrawal_request_created',
            field=models.BooleanField(default=False),
        ),
    ]
